version: '3'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - openbuild-db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=QRj8B6aYjvcB3XRSZGsnxKaZ
      - POSTGRESQL_USERNAME=openbuild_user
      - POSTGRESQL_DATABASE=openbuild

  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.11
    container_name: openbuild-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=openbuild
      - RABBITMQ_PASSWORD=hbY4n6Zc5ZzeZ7Hx
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - openbuild-rabbitmq-data:/bitnami/rabbitmq/mnesia

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - openbuild-es-data:/bitnami/elasticsearch/data

#  keycloak:
#    image: quay.io/keycloak/keycloak:21.0.1
#    restart: unless-stopped
#    volumes:
#      - ./keycloak/imports:/opt/keycloak/data/import
#    environment:
#      KC_DB_URL: jdbc:postgresql://postgresql:3306/keycloak
#      KC_DB_DATABASE: keycloak
#      KC_DB_USER: keycloak
#      KC_DB_PASSWORD: keycloak
#      KC_HTTP_ENABLED: "true"
#      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
#      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
#    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--db=postgresql", "--import-realm" ]
#    ports:
#      - "${KEYCLOAK_SERVER_PORT}:8080"
#    depends_on:
#      - postgresql

volumes:
  openbuild-db-data:
  openbuild-es-data:
  openbuild-rabbitmq-data:
